1) GOLD_TRADE_DL Table:
   --------------------

  CREATE TABLE "C##goldTrade"."GOLD_TRADE_DL" 
   (	"TYPECODE" VARCHAR2(1 BYTE) DEFAULT Null, 
	"FREQCODE" VARCHAR2(1 BYTE) DEFAULT NULL, 
	"REFPERIODID" VARCHAR2(8 BYTE) DEFAULT NULL, 
	"REFYEAR" VARCHAR2(4 BYTE) DEFAULT NULL, 
	"REFMONTH" VARCHAR2(2 BYTE) DEFAULT Null, 
	"PERIOD" VARCHAR2(6 BYTE) DEFAULT Null, 
	"REPORTERCODE" VARCHAR2(10 BYTE) DEFAULT Null, 
	"REPORTERISO" VARCHAR2(3 BYTE) DEFAULT Null, 
	"REPORTERDESC" VARCHAR2(255 BYTE) DEFAULT Null, 
	"FLOWCODE" VARCHAR2(10 BYTE) DEFAULT Null, 
	"FLOWDESC" VARCHAR2(255 BYTE) DEFAULT Null, 
	"PARTNERCODE" VARCHAR2(10 BYTE) DEFAULT Null, 
	"PARTNERISO" VARCHAR2(3 BYTE) DEFAULT Null, 
	"PARTNERDESC" VARCHAR2(255 BYTE) DEFAULT Null, 
	"PARTNER2CODE" VARCHAR2(10 BYTE) DEFAULT Null, 
	"PARTNER2ISO" VARCHAR2(3 BYTE) DEFAULT Null, 
	"PARTNER2DESC" VARCHAR2(255 BYTE) DEFAULT Null, 
	"CLASSIFICATIONCODE" VARCHAR2(10 BYTE) DEFAULT Null, 
	"CLASSIFICATIONSEARCHCODE" VARCHAR2(10 BYTE) DEFAULT Null, 
	"ISORIGINALCLASSIFICATION" VARCHAR2(10 BYTE) DEFAULT NULL, 
	"CMDCODE" VARCHAR2(10 BYTE) DEFAULT Null, 
	"CMDDESC" VARCHAR2(255 BYTE) DEFAULT Null, 
	"AGGRLEVEL" NUMBER(10,0) DEFAULT Null, 
	"ISLEAF" VARCHAR2(10 BYTE) DEFAULT Null, 
	"CUSTOMSCODE" VARCHAR2(10 BYTE) DEFAULT Null, 
	"CUSTOMSDESC" VARCHAR2(255 BYTE) DEFAULT Null, 
	"MOSCODE" VARCHAR2(10 BYTE) DEFAULT Null, 
	"MOTCODE" NUMBER(10,0) DEFAULT Null, 
	"MOTDESC" VARCHAR2(255 BYTE) DEFAULT Null, 
	"QTYUNITCODE" NUMBER(10,0) DEFAULT Null, 
	"QTYUNITABBR" VARCHAR2(20 BYTE) DEFAULT Null, 
	"QTY" NUMBER(30,5) DEFAULT Null, 
	"ISQTYESTIMATED" VARCHAR2(10 BYTE) DEFAULT Null, 
	"ALTQTYUNITCODE" NUMBER(10,0) DEFAULT Null, 
	"ALTQTYUNITABBR" VARCHAR2(20 BYTE) DEFAULT Null, 
	"ALTQTY" NUMBER(30,5) DEFAULT Null, 
	"ISALTQTYESTIMATED" VARCHAR2(10 BYTE) DEFAULT Null, 
	"NETWGT" NUMBER(30,5) DEFAULT Null, 
	"ISNETWGTESTIMATED" VARCHAR2(10 BYTE) DEFAULT Null, 
	"GROSSWGT" NUMBER(30,5) DEFAULT Null, 
	"ISGROSSWGTESTIMATED" VARCHAR2(10 BYTE) DEFAULT Null, 
	"CIFVALUE" NUMBER(30,5) DEFAULT Null, 
	"FOBVALUE" NUMBER(30,5) DEFAULT Null, 
	"PRIMARYVALUE" NUMBER(30,5) DEFAULT Null, 
	"LEGACYESTIMATIONFLAG" VARCHAR2(10 BYTE) DEFAULT Null, 
	"ISREPORTED" VARCHAR2(10 BYTE) DEFAULT Null, 
	"ISAGGREGATE" VARCHAR2(10 BYTE) DEFAULT Null
   );


2) GOLD_TRADE_DATA_REJECT Table:
   -----------------------------

  CREATE TABLE "C##goldTrade"."GOLD_TRADE_DATA_REJECT" 
   (	"TYPECODE" VARCHAR2(1 BYTE), 
	"FREQCODE" VARCHAR2(1 BYTE), 
	"REFPERIODID" VARCHAR2(8 BYTE), 
	"REFYEAR" VARCHAR2(4 BYTE), 
	"REFMONTH" VARCHAR2(2 BYTE), 
	"PERIOD" VARCHAR2(6 BYTE), 
	"REPORTERCODE" VARCHAR2(10 BYTE), 
	"REPORTERISO" VARCHAR2(3 BYTE), 
	"REPORTERDESC" VARCHAR2(255 BYTE), 
	"FLOWCODE" VARCHAR2(10 BYTE), 
	"FLOWDESC" VARCHAR2(255 BYTE), 
	"PARTNERCODE" VARCHAR2(10 BYTE), 
	"PARTNERISO" VARCHAR2(3 BYTE), 
	"PARTNERDESC" VARCHAR2(255 BYTE), 
	"PARTNER2CODE" VARCHAR2(10 BYTE), 
	"PARTNER2ISO" VARCHAR2(3 BYTE), 
	"PARTNER2DESC" VARCHAR2(255 BYTE), 
	"CLASSIFICATIONCODE" VARCHAR2(10 BYTE), 
	"CLASSIFICATIONSEARCHCODE" VARCHAR2(10 BYTE), 
	"ISORIGINALCLASSIFICATION" VARCHAR2(10 BYTE), 
	"CMDCODE" VARCHAR2(10 BYTE), 
	"CMDDESC" VARCHAR2(255 BYTE), 
	"AGGRLEVEL" NUMBER(10,0), 
	"ISLEAF" VARCHAR2(10 BYTE), 
	"CUSTOMSCODE" VARCHAR2(10 BYTE), 
	"CUSTOMSDESC" VARCHAR2(255 BYTE), 
	"MOSCODE" VARCHAR2(10 BYTE), 
	"MOTCODE" NUMBER(10,0), 
	"MOTDESC" VARCHAR2(255 BYTE), 
	"QTYUNITCODE" NUMBER(10,0), 
	"QTYUNITABBR" VARCHAR2(20 BYTE), 
	"QTY" NUMBER(30,5), 
	"ISQTYESTIMATED" VARCHAR2(10 BYTE), 
	"ALTQTYUNITCODE" NUMBER(10,0), 
	"ALTQTYUNITABBR" VARCHAR2(20 BYTE), 
	"ALTQTY" NUMBER(30,5), 
	"ISALTQTYESTIMATED" VARCHAR2(10 BYTE), 
	"NETWGT" NUMBER(30,5), 
	"ISNETWGTESTIMATED" VARCHAR2(10 BYTE), 
	"GROSSWGT" NUMBER(30,5), 
	"ISGROSSWGTESTIMATED" VARCHAR2(10 BYTE), 
	"CIFVALUE" NUMBER(30,5), 
	"FOBVALUE" NUMBER(30,5), 
	"PRIMARYVALUE" NUMBER(30,5), 
	"LEGACYESTIMATIONFLAG" VARCHAR2(10 BYTE), 
	"ISREPORTED" VARCHAR2(10 BYTE), 
	"ISAGGREGATE" VARCHAR2(10 BYTE), 
	"REJECT_REASON" VARCHAR2(255 BYTE)
   );

3) GOLD_TRADE Table:
   -----------------

  CREATE TABLE "C##goldTrade"."GOLD_TRADE" 
   (	"PERIOD" VARCHAR2(6 BYTE), 
	"TRADE_FLOW" VARCHAR2(10 BYTE), 
	"REPORTER" VARCHAR2(255 BYTE), 
	"PARTNER" VARCHAR2(255 BYTE), 
	"2ND_PARTNER" VARCHAR2(255 BYTE), 
	"CUSTOMS_DESC" VARCHAR2(255 BYTE), 
	"TRANSPORT_MODE" VARCHAR2(255 BYTE), 
	"COMMODITY_CODE" VARCHAR2(10 BYTE), 
	"TRADE_VALUE(US$)" NUMBER(30,5), 
	"NET_WEIGHT(KG)" NUMBER(30,5), 
	"GROSS_WEIGHT" NUMBER(30,5), 
	"QTY_UNIT" NUMBER(10,0), 
	"QTY" NUMBER(30,5), 
	"ALTERNATE_QUANTITY_UNIT" NUMBER(10,0), 
	"ALTERNATE_QUANTITY" NUMBER(30,5)
   );

4) GOLD_TRADE_DATA_MART Table:
   ---------------------------

  CREATE TABLE "C##goldTrade"."GOLD_TRADE_DATA_MART" 
   (	"PERIOD" VARCHAR2(6 BYTE), 
	"REPORTER" VARCHAR2(255 BYTE), 
	"PARTNER" VARCHAR2(255 BYTE), 
	"CUSTOMS_DESC" VARCHAR2(255 BYTE), 
	"TRANSPORT_MODE" VARCHAR2(255 BYTE), 
	"COMMODITY_CODE" VARCHAR2(10 BYTE), 
	"TRADE_VALUE(US$)" NUMBER(30,5), 
	"NET_WEIGHT(KG)" NUMBER(30,5), 
	 CONSTRAINT "GOLD_TRADE_DM_PK" PRIMARY KEY ("PERIOD", "REPORTER", "PARTNER", "CUSTOMS_DESC", "TRANSPORT_MODE", "COMMODITY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   );

5) GOLD_PRICE Table:
   -----------------

  CREATE TABLE "C##goldTrade"."GOLD_PRICE" 
   (	"PERIOD" VARCHAR2(6 BYTE), 
	"PRICE" NUMBER(30,5)
   );

6) BRICS_CONT Table:
   -----------------

  CREATE TABLE "C##goldTrade"."BRICS_CONT" 
   (	"PARTNER" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CONTINENT" VARCHAR2(255 BYTE), 
	"BRICS" VARCHAR2(2 BYTE), 
	"BRICS_ACCESSION" VARCHAR2(6 BYTE)
   );
